### ISSUE TITLE
With se_resnet getting AttributeError: 'list' object has no attribute 'size' ? What should i do 

### ISSUE THREAD

**Issue by ajithvallabai** [valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition#10]
Getting below error when i tried se_resnet50()

Traceback (most recent call last):
  File "train.py", line 154, in <module>
    main(args)
  File "train.py", line 92, in main
    path=save_model_path)
  File "train.py", line 111, in trainer
    optimizer=optimizer,
  File "/content/Strong_Baseline_of_Pedestrian_Attribute_Recognition/batch_engine.py", line 26, in batch_trainer
    train_logits = model(imgs, gt_label)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Strong_Baseline_of_Pedestrian_Attribute_Recognition/models/base_block.py", line 56, in forward
    logits = self.classifier(feat_map)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Strong_Baseline_of_Pedestrian_Attribute_Recognition/models/base_block.py", line 20, in forward
    feat = self.avg_pool(feature).view(feature.size(0), -1)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/pooling.py", line 1031, in forward
    return F.adaptive_avg_pool2d(input, self.output_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 767, in adaptive_avg_pool2d
    _output_size = _list_with_default(output_size, input.size())
AttributeError: 'list' object has no attribute 'size'

**Comment by valencebond** [comment]
i will check it soon

**Comment by ajithvallabai** [comment]
```
def features(self, x):
        x = self.layer0(x)
        x = self.layer1(x)
        x2 = self.layer2(x)
        x3 = self.layer3(x2)
        x4 = self.layer4(x3)
        return [x2, x3, x4]
```
In above function we have to change the return value as below
```
return x4
```
