### ISSUE TITLE
Resnet18 as backbone instead of 50

### ISSUE THREAD

**Issue by oqpti** [valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition#17]
As the title suggests, I'd like to use Resnet18 as the feature extractor for performance reasons. However, I receive this error log when I try.

------------------------------------------------------------
use GPU0 for training
train set: PETA trainval, test set: test
Compose(
    Resize(size=(256, 192),
    interpolation=PIL.Image.BILINEAR)
    Pad(padding=10, fill=0, padding_mode=constant)                                                                                                                              
    RandomCrop(size=(256, 192), padding=None)                                                                                                                                   
    RandomHorizontalFlip(p=0.5)                                                                                                                                                 
    ToTensor()                                                                                                                                                                  
    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])                                                                                                        )
trainval set: 11400, test set: 7600, attr_num : 35                                                                                                                          Traceback (most recent call last):                                                                                                                                            
  File "train.py", line 149, in <module>                                                                                                                                        
    main(args)                                                                                                                                                                
  File "train.py", line 89, in main                                                                                                                                             
    path=save_model_path)                                                                                                                                                     
  File "train.py", line 108, in trainer                                                                                                                                         
    optimizer=optimizer,                                                                                                                                                      
  File "/home/colin/project_dir/batch_engine.py", line 26, in batch_trainer                                                                                                     
    train_logits = model(imgs, gt_label)                                                                                                                                      
  File "/home/colin/project_dir/pyvenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__                                                          
    result = self.forward(*input, **kwargs)                                                                                                                                   
  File "/home/colin/project_dir/pyvenv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward                                                    
    return self.module(*inputs[0], **kwargs[0])                                                                                                                               
  File "/home/colin/project_dir/pyvenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__                                                           
    result = self.forward(*input, **kwargs)                                                                                                                                   
  File "/home/colin/project_dir/models/base_block.py", line 56, in forward                                                                                                      
    logits = self.classifier(feat_map)                                                                                                                                        
  File "/home/colin/project_dir/pyvenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__                                                           
    result = self.forward(*input, **kwargs)                                                                                                                                   
  File "/home/colin/project_dir/models/base_block.py", line 21, in forward                                                                                                      
    x = self.logits(feat)                                                                                                                                                     
  File "/home/colin/project_dir/pyvenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__                                                           
    result = self.forward(*input, **kwargs)                                                                                                                                   
  File "/home/colin/project_dir/pyvenv/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward                                                         
    input = module(input)                                                                                                                                                     
  File "/home/colin/project_dir/pyvenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__                                                           
    result = self.forward(*input, **kwargs)                                                                                                                                   
  File "/home/colin/project_dir/pyvenv/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward                                                             
    return F.linear(input, self.weight, self.bias)
  File "/home/colin/project_dir/pyvenv/lib/python3.6/site-packages/torch/nn/functional.py", line 1370, in linear 
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [64 x 512], m2: [2048 x 35] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290

Is this supported? I can replace resnet50 with resnet101, but both 18 and 34 produce the same error.

**Comment by valencebond** [comment]
you should change the [input channels](https://github.com/valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition/blob/5363c9859dc87b79e39a2b353a6a6eb8185d5c6f/models/base_block.py#L11) to fit the model's output channels, 512  for resnet18 and resnet34
