### ISSUE TITLE
AttributeError: 'list' object has no attribute 'size'

### ISSUE THREAD

**Issue by qianjinhao** [valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition#2]
when i change the backbone:
backbone = se_resnext101_32x4d()
some bug happened.

Traceback (most recent call last):
  File "train.py", line 152, in <module>
    main(args)
  File "train.py", line 92, in main
    path=save_model_path)
  File "train.py", line 111, in trainer
    optimizer=optimizer,
  File "/media/data2/qianjinhao/Strong_Baseline_of_Pedestrian_Attribute_Recognition/batch_engine.py", line 26, in batch_trainer
    train_logits = model(imgs, gt_label)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/data2/qianjinhao/Strong_Baseline_of_Pedestrian_Attribute_Recognition/models/base_block.py", line 56, in forward
    logits = self.classifier(feat_map)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/data2/qianjinhao/Strong_Baseline_of_Pedestrian_Attribute_Recognition/models/base_block.py", line 20, in forward
    feat = self.avg_pool(feature).view(feature.size(0), -1)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/pooling.py", line 1031, in forward
    return F.adaptive_avg_pool2d(input, self.output_size)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 767, in adaptive_avg_pool2d
    _output_size = _list_with_default(output_size, input.size())
AttributeError: 'list' object has no attribute 'size'

**Comment by ajithvallabai** [comment]
@qianjinhao  were u able to find the solution ? i am also facing it with se_resnet50()
